title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brendanrjohnson.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brendanrjohnson
   twitter: 
   facebook: brendanrjohnson
   email: brendan.r72.johnson@gmail.com

google_analytics: "UA-58263416-1"
